releases:
  - name: atlassian-jira-software
    namespace: atlassian
    chart: ./atlassian-jira-software
    values:
      - ingress:
          enabled: true
          hosts:
            - jira.{{ requiredEnv "DEVOPS_DOMAIN" }}
        jira:
          javaHeapSize: 2048m
          reverseProxyHost: jira.{{ requiredEnv "DEVOPS_DOMAIN" }}
          # Disable websudo for SAML or OIDC
          javaOptions: "-Djira.websudo.is.disabled=true"
        resources:
          limits:
            # for single core CPU
            cpu: 800m
            memory: 2560Mi
          requests:
            cpu: 0
            memory: 2560Mi

  - name: atlassian-confluence
    namespace: atlassian
    chart: ./atlassian-confluence
    values:
      - ingress:
          enabled: true
          hosts:
            - confluence.{{ requiredEnv "DEVOPS_DOMAIN" }}
        confluence:
          reverseProxyHost: confluence.{{ requiredEnv "DEVOPS_DOMAIN" }}
        resources:
          limits:
            # for single core CPU
            cpu: 800m
            memory: 2048Mi
          requests:
            cpu: 0
            memory: 2048Mi