apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
  namespace: atlassian
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 100Gi